# Generated by Django 3.0.6 on 2020-09-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
