# Generated by Django 3.0.6 on 2020-09-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tutorial_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='photo',
            field=models.ImageField(null=True, upload_to='main/'),
        ),
    ]
