# Generated by Django 3.0.6 on 2020-09-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200929_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_title', models.CharField(max_length=200)),
                ('cake_content', models.TextField()),
                ('cake_id', models.IntegerField()),
                ('photo', models.ImageField(null=True, upload_to='main/')),
            ],
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
